name: 1on1-questions-action
description: "Attach a list of random 1 on 1 questions to an issue"
author: Pierluigi Cau

branding:
  icon: help-circle
  color: green

inputs:
  num-questions: # amount of questions per category
    description: "How many questions to be generated per category"
    required: true
    default: "1"
  label: # the label that when applied triggers this workflow
    description: "The label to trigger this workflow"
    required: true
    default: "1on1"
outputs:
  respone:
    description: "The issue response"
runs:
  using: "node12"
  main: "index.js"
